### ISSUE TITLE
Block order in VS Code tree list

### ISSUE THREAD

**Issue by mikedotmundy** [Triumph-Tech/magnus-vscode#1]
I am wondering if it is possible to change the order of the blocks in the tree in VS Code. See screen shot below. 

<img width="498" alt="image" src="https://user-images.githubusercontent.com/23226974/195084374-35689f8f-5d85-4950-8e3f-6e0514756791.png">

This is my homepage, and the blocks are obviously in alphabetical order instead of the order they are on the page. This is a little confusing for bigger pages that have a lot of blocks. So, is there any way to have them order by the way they appear on the page and not alphabetical?

**Comment by jonedmiston** [comment]
Thanks Mike! Yes, the order of the block is currently alphabetical by name. The zone locations are difficult to infer as they are defined in a theme's layout HTML markup. For now we'll make a hard coded configuration that puts the common system zones in a specific order. It won't be perfect (someone could move the Login zone to the bottom) and custom zone names will appear at the bottom of the list, but it should be better than alpha order.

Long-term we may be able to parse the layout mark-up.

**Comment by jonedmiston** [comment]
Fixed in: https://github.com/Triumph-Tech/Triumph-Rockit/commit/6ba11bd59cc402e411d1d0f16b6b8d2da5c24f2b
