### ISSUE TITLE
Unexpected Response Received From The Server

### ISSUE THREAD

**Issue by mikedotmundy** [Triumph-Tech/magnus-vscode#12]
I am getting an error "Unexpected Response Received From The Server" when I attempt to expand an HTML Block in the navigation that has no content in it.
<img width="360" alt="Screenshot 2023-05-05 at 20 08 40" src="https://user-images.githubusercontent.com/23226974/236587453-2cc7fa71-20a9-416f-9898-17a3b19757b9.png">
<img width="1705" alt="Screenshot 2023-05-05 at 20 07 46" src="https://user-images.githubusercontent.com/23226974/236587457-df9af811-18dc-4cd3-829a-068c4ae9d023.png">

Again, this only happens when there is no content in the HTML block. As soon as I add content in the block (from my web browser), the navigation in VS Code works and I can open the HTML block in VS Code.

**Comment by bradencohen** [comment]
@mikedotmundy this has been fixed in v1.2, which is now available in the Rock Shop.

**Comment by mikedotmundy** [comment]
Thank you!
