### ISSUE TITLE
Magnus is unable to authenticate if forms authentication cookie does not start with .ROCK=

### ISSUE THREAD

**Issue by tp-code** [Triumph-Tech/magnus-vscode#13]
We recently had an issue with a workflow that cause many emails to go to the wrong individual with some other person's impersonation link. As part of the solution, we invalidated all logins by following a community recipe to renamed our forms authentication cookie ([https://community.rockrms.com/recipes/69/rock-impersonation-token-leak-rckipid-](https://community.rockrms.com/recipes/69/rock-impersonation-token-leak-rckipid-))

Now when we try to login to Magnus we get an error: **Unable to authorize with the server.**
<img width="501" alt="Screenshot 2023-11-08 at 2 35 05 PM" src="https://github.com/Triumph-Tech/magnus-vscode/assets/41316251/d2737d16-44e6-40ee-aa2f-78a89b7ffa8d">

This appears to be because Magnus is hard coded to look for a cookie beginning with ".ROCK"
[https://github.com/Triumph-Tech/magnus-vscode/blob/afaa0a7fff3e1ac31f3a856a9b6f63038ace0ad6/src/api.ts#L125C89-L125C89](https://github.com/Triumph-Tech/magnus-vscode/blob/afaa0a7fff3e1ac31f3a856a9b6f63038ace0ad6/src/api.ts#L125C89-L125C89)
<img width="751" alt="Screenshot 2023-11-08 at 2 38 00 PM" src="https://github.com/Triumph-Tech/magnus-vscode/assets/41316251/cd93b7b2-ac09-420b-afe8-aaaf65db9b9d">

Is it possible to change this functionality? I could see other instances where an organization wants/needs to change their cookie name.

**Comment by cabal95** [comment]
Rock v17 introduces a new feature where you can expire all existing authentication cookies. Since Rock does not officially support an authentication cookie name other than `.ROCK` we believe that will be the better path forward.
