### ISSUE TITLE
"Edit on Web" Option for Mobile App Pages Links to AppleTV Route

### ISSUE THREAD

**Issue by briankalwat** [Triumph-Tech/magnus-vscode#14]
Currently, right-clicking on a mobile app page in Magnus and clicking "Edit on Web", it tries to open the page using the `appletv-applications` route instead of the `mobile-applications` route.

Route currently used for mobile apple pages:
`/admin/cms/appletv-applications/{SiteId}/{PageId}`

Correct route for mobile app pages:
`/admin/cms/mobile-applications/{SiteId}/{PageId}`

**Comment by bradencohen** [comment]
Hey Brian, would you mind verifying that Magnus is on the latest version? This bug was internally reported and marked as fixed in the latest version.

Thanks!

**Comment by briankalwat** [comment]
@bradencohen just updated and can confirm it is fixed. 🔥
