### ISSUE TITLE
Helix Icons Not Visible for Lava Applications/Blocks/Endpoints

### ISSUE THREAD

**Issue by briankalwat** [Triumph-Tech/magnus-vscode#19]
This might just be an update for Magnus that isn't available yet, but I'm not seeing the icons for Helix applications/blocks/endpoints that are shown in the documentation.

<img width="364" alt="image" src="https://github.com/user-attachments/assets/3b21bf80-d71d-4ff1-b178-b805875d5a97">

<img width="272" alt="image" src="https://github.com/user-attachments/assets/3c10c62f-3d75-4c1c-a4a3-846ca092aa7f">

**Comment by bradencohen** [comment]
Fixed, we actually include the icons in the Helix plugin package so this will be resolved in the v1 release.
