### ISSUE TITLE
Changes Made to Lava Shortcodes Not Reflected on Page Refresh

### ISSUE THREAD

**Issue by briankalwat** [Triumph-Tech/magnus-vscode#4]
This morning I tried editing a lava shortcode and the change wasn't immediately reflected on a page where it is used (I tried hard refreshing, as well).

After experiencing this, I checked the shortcode in the Rock UI, and the change I had made via Magnus was visible there.

Once I re-saved the shortcode in the UI, the page then reflected the change. It's as if the shortcode is cached somehow, however cacheability type on the page the shortcode is used is set to `no-cache`, and cache duration on the html block where the shortcode was used is set to `0`.

**Comment by jonedmiston** [comment]
v1.0 should be out today or tomorrow.
