### ISSUE TITLE
Magnus changes UTF-8 Encoded Characters to "?"

### ISSUE THREAD

**Issue by garrettjohnson** [Triumph-Tech/magnus-vscode#6]
When opening an HTML content block with a UTF-8 encoded character, magnus converts the character to a question mark. Discovered because the entity command page had question marks where quotes should be.

**To replicate** 
1. Paste the following into a HTML Content block using the web interface:
```
won’t ™
```
2. Open in Magnus. Observe that the text now renders as
```
won?t ?
```
3. Save from Magnus.
4. Reload the page using the web interface and observe that the HTML Content block is rendering `won?t ?`

Running VSCode Magnus 1.0.2

**Comment by briankalwat** [comment]
Praise God for this fix! 😂 Can't wait! ❤️

**Comment by jonedmiston** [comment]
v1.0 should be out today or tomorrow.
