### ISSUE TITLE
Requested resource was not found error

### ISSUE THREAD

**Issue by dataCollegechurch** [Triumph-Tech/magnus-vscode#7]
### Description

When I go to expand my server in the magnus window within VS Code I get this error "Requested resource was not found"
![image](https://user-images.githubusercontent.com/54962439/201424011-7fe38e3e-9f6f-4743-9362-6f5daf6d9125.png)

Fiddler indicates this is the request and the status code is 404
![image](https://user-images.githubusercontent.com/54962439/201423065-2cc1fe25-6f12-40d5-b843-efce61ec52e8.png)

### Steps to Reproduce

1. Install Magnus VS Code Extension
2. Install the Magnus Plugin on your server from the Rock Shop
3. Configure Magus to all physical directories and enable all virtual filesystems
![image](https://user-images.githubusercontent.com/54962439/201423747-d51f9491-6c27-4266-8631-22035bd2d1a9.png)
5. Open VS Code and add server in my case https://rockdev.college-church.org/, username and password
6. Expand Server

**Expected behavior:**

Server content is displayed

**Actual behavior:**

Requested resource was not found error is displayed instead

What I have confirmed:

1. my username and password work to login to Rock via database authentication. 
2. my public ip address is added to the allowed ip on the magnus editor page

### Versions
Rock Magnus Plugin Version: Public Beta
Rock Version: Rock McKinley 14.0 (1.14.0.18)
Client Culture Setting: en-US
VS Code Details
Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Comment by cabal95** [comment]
Just some additional details from a discussion in Rocket Chat, Tony was able to confirm that the API endpoints are not showing up in Admin Tools, Security, REST Controllers. So it seems like they are somehow not being detected/registered by Rock.

**Comment by jonedmiston** [comment]
Sounds like a core issue. Can you clear your exception log and restart rock.

**Comment by dataCollegechurch** [comment]
I have cleared my exception log and restarted rock. Unfortunately, I am not seeing any new exceptions or change in behavior.

**Comment by nairdo** [comment]
Tony @dataCollegechurch , I don't mean to be redundant if someone already asked you about this via chat/elsewhere, but can you confirm that the Rest Controller and Endpoints also do not register when you click the "Requery REST Data" button on the bottom of the REST Controllers page?:

![image](https://user-images.githubusercontent.com/383807/213209908-fe278c34-2cbe-4150-97fb-a4f757c78f1e.png)

I'm not saying that should be required, but I just want to know if that work-around works.

**Comment by dataCollegechurch** [comment]
@nairdo - I have not tried that work-around up to this point. Unfortunately, I did not see any new Rest controllers after click the "Requery Rest Data" link.

**Comment by dataCollegechurch** [comment]
I refreshed our dev server with a copy of prod database. I had not installed magnus on prod yet, so I was able to reinstall mangus from scratch and did not encounter the error. It is possible one or more files was corrupted in dev. Perhaps a tool like Arena's Verify Files/Database tool could come in handy for identifying corrupted or customized core files in the future.

**Comment by dataCollegechurch** [comment]
This issue was cleared up in Dev after I copied our production database to Dev. Now I am trying to make use of Magnus in Production and I am seeing the same error message.

**Comment by jonedmiston** [comment]
@dataCollegechurch anything new to report on this?

**Comment by dataCollegechurch** [comment]
@jonedmiston - I haven't tried this out in a while, but made another attempt today and now it is working. I am not sure what changed but let's go ahead and close this issue.

**Comment by jonedmiston** [comment]
@dataCollegechurch ok thanks for the update.
